### ISSUE TITLE
[DataCap Application] Cell Painting Gallery

### ISSUE THREAD

**Issue by lijo76618** [stcloudlisa/Allocator-Pathway-Data#13]
### Data Owner Name

Broad Institute

### Data Owner Country/Region

United Kingdom

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/cellpainting-gallery/

### Social Media Handle

https://registry.opendata.aws/cellpainting-gallery/

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Preparer

### Total amount of DataCap being requested

4PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1loi6wv6mn7ou42filsdkuwp7rw723eznrorsynq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.

```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Disclaimer: 
Due to un-answered issues around whether combined requests or duplicate requests can be used to apply LDN. This is a series of recent new open datasets never applied by anybody (aka calling dibs).

Description: 
The Cell Painting Gallery is a collection of image datasets created using the Cell Painting assay. The images of cells are captured by microscopy imaging, and reveal the response of various labeled cell components to whatever treatments are tested, which can include genetic perturbations, chemicals or drugs, or different cell types. 

s3://cellpainting-gallery
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Singapore

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
After we download data from the Internet, the data is cut into disks through Singularity, and then the hard disk is mailed to the SPs.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Yes, but considering that some data expires, the number of backups is limited, so I want to store this data again
```

### Please share a sample of the data

```text
https://registry.opendata.aws/cellpainting-gallery/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03151449, Shenzhen, China           
f03151456, Shenzhen, China               
f03179570, Singapore       
f03179555, Singapore           
f03178077, Tokyo, Japan   
f03178144, Tokyo, Japan   
f03179572, US 
f03214937, US 
f03229932, South Korea
f03229933, South Korea
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by stcloudlisa** [comment]
How do you plan to ensure the security and privacy of the Cell Painting Gallery datasets that will be stored on the Filecoin network? Considering these datasets contain sensitive biomedical information, are there specific encryption measures or access control policies in place to protect the data from unauthorized access?

**Comment by lijo76618** [comment]
Dear, this is a public dataset, and all the data is accessible. Our storage on the Filecoin network is also public
